# Generated by Django 4.2.4 on 2023-08-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newswave_api', '0002_remove_newsitem_images_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
