# Generated by Django 4.2.4 on 2023-08-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newswave_api', '0003_rename_images_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsItem',
            new_name='News',
        ),
    ]
