# Generated by Django 4.2.4 on 2023-08-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newswave_api', '0004_rename_newsitem_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News'},
        ),
    ]
