# Generated by Django 4.2.4 on 2023-08-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newswave_api', '0006_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
